[workspace]
resolver = "3"
members = [
    "crates/vildlang",
]

default-members = [
    "crates/vildlang",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
authors = ["Silvija Ivanovaite"]
license = "MIT"
repository = "https://github.com/vildrose/vildlang"
homepage = "https://github.com/vildrose/vildlang"
keywords = []
categories = []

[workspace.dependencies]
# Currently just using git directly, without tagged release
vildrose-core = { git = "https://github.com/vildrose/core" }

proptest = "1"
insta = { version = "1", features = ["ron"] }
criterion = { version = "0.5", features = ["html_reports"] }

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unused_results = "warn"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"

[profile.bench]
opt-level = 3
debug = true
lto = "thin"
codegen-units = 1
strip = "none"
